export type RequestStatus='DRAFT'|'PUBLISHED'|'HAS_APPLICANTS'|'ASSIGNED'|'IN_PROGRESS'|'PENDING_CONFIRMATION'|'COMPLETED'|'CANCELLED';
export type ApplicationStatus='PENDING'|'SELECTED'|'REJECTED'|'DECLINED'|'CANCELLED';export type Urgency='NORMAL'|'URGENT';
